---
title: " "
output:
  pdf_document:
    number_sections: TRUE
geometry: "left = 2cm, right = 2cm, top = 2cm, bottom = 2cm"
fontsize: 12pt
header-includes:
  - \usepackage{setspace}\spacing{1.5}
  
bibliography: References.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!---TITLE PAGE--->

```{=tex}
\begin{centering}


\large

{\bf "SIS, ARE YOU OKAY?": A FACTOR ANALYSIS TO IDENTIFY THE RAMIFICATIONS OF SYSTEMIC RACISM ON THE PSYCHOLOGICAL WELL-BEING OF BLACK WOMEN IN U.S. AMERICAN ACADEMIA}

\vspace{1.5 cm}

\singlespace

\normalsize
Authored By

\vspace{0.5 cm}
\large

{\bf BENNETT McAULEY\\ KATELYN SETTLEMYRE\\ \& \\ DIDIER TURCIOS}

{\bf North Carolina State University\\ Department of Statistics}

\vspace{1.5 cm}

\normalsize

in partial fulfillment of the requirements for\\ the degree of Master of Statistics;\\ and in collaboration with our client et al.:

\vspace{1 cm}

\large

{\bf JOCELYN TALIAFERRO, MSW, PhD}

{\bf North Carolina State University\\ School of Social Work}

{\bf \& \\ DIAMOND MEADOWS, MSW}

{\bf East Tennessee State University\\ Department of Psychology}

\vspace{1.5 cm}

\normalsize
{May 2023}

\end{centering}
```

<!---INTRODUCTION & OTHER CONTENT STARTS HERE--->

\newpage
\doublespacing

# Introduction

|       The United States has a persistent history of encouraging and enforcing discrimination, oppression, and other forms of prejudice against African Americans, who are often simply characterized as "Black". The turbulent relationship between the Black community and the institutions of government, education, healthcare, law enforcement, social services, and even housing, is a compounded byproduct of historical bylaws--most infamously, the era of Jim Crow laws (c. 1877-1964)--that have yet to be unraveled from the fabric of U.S. American culture and politics.

|       Racially-motivated violence has been the cornerstone of the Black experience for the entirety of the community's documented history. Paradoxically, Black people are more susceptible to bouts of national trepidation but are expected to show the most resilience. With the additional intersection of gender, Black *women* are especially vulnerable but are often neglected in policies and actions designed to alleviate the stressors of U.S. residents.

|       In the spring of 2020, the deficit of adequate resources for Black women was proven evident with the surge of COVID-19 and the subsequent deaths of George Floyd and Breonna Taylor. Even with nationwide attention on these issues, Black women continued to suffer in silence under the pretense that they are "strong": perpetually shouldering the burdens of others with no space for their own (Pappas, 2021). Consequently, Black women as a population experience disparities in quality of life that no other group in the U.S. do, most of which can be attributed to social-environmental factors. They are at higher risk for breast cancer, stroke, diabetes, and hypertension; the Black community overall experienced two to three times more complications or death from COVID-19 than the general U.S. population (Menifield & Clark, 2021). Concerning mental health, Black women are half as likely to seek services compared to their white counterparts, and documented studies suggest one reason for this is the lack of cultural competency among providers (Abrams et al., 2018).

|       In the context of this study, the population of interest is Black women in academia. They make up 4% of college and university faculty, among whom they must navigate unwelcoming--sometimes hostile--environments (NCES, 2020). The barriers previously mentioned have contributed to the marginalization and isolation of Black women in academia. By examining potential associations extracted from respondent data, methods for healthy and impactful coping mechanisms can be identified. Data is derived from a survey conducted in April 2022, to learn how Black women were coping post-pandemic. Approximately 2680 participants responded to 70 questions. In addition to demographic information, the topics covered in the survey included COVID-19, anti-Black racism, depression, anxiety, and coping. The analysis presented in the following sections is driven by structural modeling methods. In lieu of significance testing,  the objective of the study is to determine prominent factors that influence the extent to which Black women suffer from depression, anxiety, and other mental health issues.

<!---METHODS PAGE--->

# Data Analysis Methodology

## The Data
|       A survey was conducted via a paid panel to find out how Black women across the United States were coping.  Data was collected in April 2022, gathering 2631 respondents. The survey consisted of 70 questions, asking about the following domains: COVID-19, Anti-Black Racism, Depression, Anxiety, and Demographic information.  
|       The raw data consists of 157 variables and 2631 subjects. Since this research focuses on Black women, there were questions to screen out subjects who were not Black adult females that consented to the survey. Removing subjects who were screened out, there were 2260 subjects that fit the requirements. Variables that were irrelevant to analysis were also removed, such as personal information or variables that had been recoded, leaving 80 variables for analysis. The data has also been validated, checking for potential duplications in the event a respondent had to restart the survey, and ensuring values for a given variable are all of the same type (e.g., all ‘age’ values are numeric). __*Missing data is handled how? Or do we mention this right now?*__  
*what else?*


## Structural Equation Modeling (SEM)

|       Structural Equation Modeling (SEM) is a technique for investigating relationships by specifying a model that represents predictions of that theory among plausible constructs measured with appropriate observed variables (Hayduk, Cummings, Boadu, Pazderka-Robinson, & Boulianne, 2007). SEM can be thought of as a combination of regression analysis and factor analysis; it uses *latent* variables or constructs that are measured by multiple observed variables or indicators. For example, a SEM model can be used to estimate the association between outcomes, such as levels of depression or anxiety, and underlying attitudes that influence those, such as coping mechanisms and the effects of Covid-19 or anti-Black racism. SEM allows us to include multiple influences, to allow unobserved concepts that control for the observed indicators, to specify how those concepts influence one another, to assess the model’s overall compatibility to the data, and to determine whether how well the model fits the data (Chapman & Feit, 2019). 

![A model measuring levels of depression and anxiety. In this model, coping ability and strategies is associated with Covid-19 and anti-Black racism factors, while the overarching response to *Are you okay?* closely relates to both Covid-19 and anti-Black racism influences, which is then associated to levels of depression and anxiety.](Methods - SEM Model.jpg)

|       To use SEM as an analysis tool, a graphical path diagram of influences is first created. Then, the strengths of the relationships for each path in the model are estimated. The paths in the model can be categorized as either observed variables, i.e., have data points, or latent variables that may underlie the observed data. A model is then fitted to the data, using the structural model paths created. Figure 1 demonstrates how an SEM model can be constructed to investigate the objectives of this study. For example, the Covid-19 latent variable can be observed as survey items Q1, Q2, and Q3. More complexly, the Coping latent variable can be observed by both survey items *and* other latent variables (i.e., Covid-19, anti-Black racism, etc). Upon fitting the SEM model, the strength of the relationships between the latent variables are compared, as well as the degree to which the model fits the observed data. Alternative models may then be fitted and compared to the original (full) model.  

## Exploratory Factor Analysis (EFA)

|       In Chapter 8.3 of *R For Marketing Research and Analysis*, Chapman and Feit (2019) describe Exploratory Factor Analysis (EFA) as a family of techniques used to assess the relationship of *constructs* (concepts) in surveys and psychological assessments. Factors are regarded as *latent variables* that cannot be observed directly--as one might in a simple linear model--but are associated through their relationship to other variables. For example, abstract concepts such as intelligence, personal preference, and emotions are not observable independently or empirically. Instead, they are measured with a number of indicators known as *manifest variables*, which are empirical factors and behaviors(e.g. GPA, survey responses, and so on) that, in tandem, provide an imperfect explanation to the underlying latent variables.

|       The goal of EFA is to find the degree to which the latent variables account for observed the variance of the manifest variables. The result is similar to Principle Components Analysis (PCA), where linear combinations or mixtures of the initial variables reduce the dimensionality of the data while retaining as much information as possible. What separates EFA from PCA, however, is the interpretability of the loadings on the variables. In other words, EFA optimizes solutions that favor intuition in terms of the original variables so the user can test whether the data is consistent with expectations.

|       To find a solution using EFA the following steps are generally implemented with a variety of tools and techniques:
|           1. **Determine the number of factors to estimate and test**. In R, this can be done by constructing a            *scree plot*, a line plot of the eigenvalues of factors or principal components and retaining the ones that are greater than 1.0. An eigenvalue of 1.0 corresponds to the amount of variance that can be attributed to a single independent variable.

|           2. **Extract factors for modeling**. Determine the variable loadings using PCA, maximum likelihood, or other methods to select the $k$ (limited to the number suggested in Step 1) factors to include and interpret. Trying more than one value of $k$--none beyond $k \pm 1$--is recommended to determine which model yields stronger interpretability.

|           3. **Rotate the loadings**. The purpose of rotation is to determine whether correlation between factors should be allowed or not. Software cannot interpret the context of the *latent variables*, but rotation can assist in deciding if, conceptually, factors should be considered independent or if it makes more sense for them to be related. One of two types of rotations can be applied: *orthogonal* and *oblique*. Orthogonal rotation, as its name implies, assumes that factors *do not* correlate. While this method is the default among most software and languages, it is not always the more plausible. Oblique rotation, on the other hand, assumes that factors can and *do* correlate, and considers how.

## Why these methods?
|       The parameters of interest for this study are depression and anxiety. One might wonder, why not use regression methods? However, where regression aims to predict a given variable, we are instead interested in the relationship between variables. Both SEM and EFA aim to explain relationships between variables. Additionally, depression and anxiety are not able to be measured directly, meaning they are latent variables, making these methods good options for our data.  
|       One can see data has high dimensionality. These methods have also been chosen for dimension reduction. Why, then, do we not use principal component analysis (PCA)? PCA seems like a good option since it is also a dimension reduction technique. However, the goal of PCA is to capture as much variability as possible with linear combinations of the variables, called principal components (PCs). It does not make model assumption, whereas EFA and SEM propose models and tests whether the data fits those models. In PCA, the PCs cannot be interpreted since there is no underlying structure. Our chosen methods have constructs that are able to be easily interpreted.  
*EFA and SEM are similar. How do they differ and why do we want this?*  


<!---CITATIONS PAGE--->

\newpage

# References

---
nocite: '@Pappa, @Menif, @Abram, @NCES, @Chapm'
---
